[project]
name = "llama-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "hf-transfer>=0.1.9",
    "loguru>=0.7.3",
    "peft>=0.17.1",
    "pydantic>=2.12.2",
    "pyyaml>=6.0.3",
    "transformers>=4.57.1",
    "vllm>=0.11.0",
]

[project.scripts]
infer = "llama_inference.cli.inference:main"

[tool.setuptools]
package-dir = {"" = "src"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
